import type { PosProduct } from "../../lib/pos-types";

export const productVisuals = [
  {
    tone: "from-slate-50 to-slate-100",
    accent: "text-slate-300",
  },
  {
    tone: "from-slate-50 to-slate-100",
    accent: "text-slate-300",
  },
  {
    tone: "from-zinc-50 to-slate-100",
    accent: "text-slate-300",
  },
  {
    tone: "from-cyan-50 via-white to-indigo-100",
    accent: "text-cyan-700",
  },
  {
    tone: "from-stone-50 via-white to-amber-100",
    accent: "text-stone-600",
  },
  {
    tone: "from-emerald-900 via-teal-500 to-lime-200",
    accent: "text-lime-100",
  },
  {
    tone: "from-neutral-50 via-white to-rose-100",
    accent: "text-rose-400",
  },
  {
    tone: "from-zinc-100 via-white to-neutral-200",
    accent: "text-zinc-800",
  },
  {
    tone: "from-neutral-900 via-stone-700 to-orange-300",
    accent: "text-orange-100",
  },
  {
    tone: "from-fuchsia-200 via-sky-200 to-lime-200",
    accent: "text-fuchsia-700",
  },
  {
    tone: "from-amber-50 via-white to-orange-100",
    accent: "text-orange-700",
  },
] as const;

export const fallbackProducts: PosProduct[] = [
  {
    id: "prod_invoice",
    product_type: "SERVICE",
    name: "Rechnung",
    category: "Service",
    price: 0,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "SERVICE",
  },
  {
    id: "prod_service_personal",
    product_type: "SERVICE",
    name: "Service Personal",
    category: "Service",
    price: 0,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "SERVICE",
  },
  {
    id: "prod_shisha_standard",
    product_type: "BASIC",
    name: "Shisha Standard",
    category: "Shisha",
    price: 3000,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_nava_shisha",
    product_type: "BASIC",
    name: "NAVA Shisha",
    category: "Shisha",
    price: 5900,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_smokezilla_laser_shisha",
    product_type: "BASIC",
    name: "SmokeZilla Laser Shisha",
    category: "Shisha",
    price: 8900,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_shisha_triple_skull",
    product_type: "BASIC",
    name: "Shisha Triple Skull",
    category: "Shisha",
    price: 4500,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_neuer_kopf",
    product_type: "SERVICE",
    name: "Neuer Kopf",
    category: "Shisha",
    price: 1500,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_kohle",
    product_type: "SERVICE",
    name: "Kohle",
    category: "Shisha",
    price: 0,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_mundstucke",
    product_type: "SERVICE",
    name: "Mundstucke",
    category: "Shisha",
    price: 300,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
  {
    id: "prod_chinotto",
    product_type: "BASIC",
    name: "Chinotto",
    category: "Sussgetranke",
    price: 700,
    tax_code_id: "tax_standard_ch",
    tax_code_name: "MwSt 8.1%",
    tax_rate_bps: 810,
    is_available: true,
    station: "BAR",
  },
];
